# -*- coding: utf-8 -*-
"""Pivot_table_anudip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5hhhm1C28xLVvtPOIoGhkuW0U1X1hY1
"""

import pandas as pd

df = pd.read_csv('/content/salesdata.csv')
df

df.pivot_table(index=['Region','Item'],values='Units',aggfunc='sum')

df.pivot_table(index=['Manager'],values='Sale_amt',aggfunc={'Sale_amt':['mean','count']})

